// Fallback for using MaterialIcons on Android and web.

import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { SymbolViewProps, SymbolWeight } from 'expo-symbols';
import { ComponentProps } from 'react';
import { OpaqueColorValue, type StyleProp, type TextStyle } from 'react-native';

type IconMapping = Record<SymbolViewProps['name'], ComponentProps<typeof MaterialIcons>['name']>;
type IconSymbolName = keyof typeof MAPPING;

/**
 * Add your SF Symbols to Material Icons mappings here.
 * - see Material Icons in the [Icons Directory](https://icons.expo.fyi).
 * - see SF Symbols in the [SF Symbols](https://developer.apple.com/sf-symbols/) app.
 */
const MAPPING = {
  'house.fill': 'home',
  'paperplane.fill': 'send',
  'chevron.left': 'chevron-left',
  'chevron.right': 'chevron-right',
  'star.fill': 'star',
  'person.fill': 'person',
  'car.fill': 'directions-car',
  'calendar': 'calendar-today',
  'clock': 'access-time',
  'location': 'location-on',
  'phone.fill': 'phone',
  'message': 'message',
  'settings': 'settings',
  'wallet': 'account-balance-wallet',
  'search': 'search',
  'filter': 'filter-list',
  'sort': 'sort',
  'checkmark': 'check',
  'xmark': 'close',
  'plus': 'add',
  'minus': 'remove',
  'edit': 'edit',
  'delete': 'delete',
  'share': 'share',
  'bookmark': 'bookmark',
  'heart': 'favorite',
  'eye': 'visibility',
  'eye.slash': 'visibility-off',
  'lock': 'lock',
  'unlock': 'lock-open',
  'shield': 'security',
  'warning': 'warning',
  'info': 'info',
  'question': 'help',
  'camera': 'camera-alt',
  'photo': 'photo',
  'microphone': 'mic',
  'speaker': 'volume-up',
  'speaker.slash': 'volume-off',
  'wifi': 'wifi',
  'bluetooth': 'bluetooth',
  'battery': 'battery-full',
  'signal': 'signal-cellular-4-bar',
  'map': 'map',
  'navigation': 'navigation',
  'compass': 'explore',
  'flag': 'flag',
  'pin': 'room',
  'marker': 'place',
  'traffic': 'traffic',
  'parking': 'local-parking',
  'gas': 'local-gas-station',
  'repair': 'build',
  'tire': 'tire-repair',
  'key': 'vpn-key',
  'card': 'credit-card',
  'money': 'attach-money',
  'coins': 'monetization-on',
  'gift': 'card-giftcard',
  'discount': 'local-offer',
  'percent': 'percent',
  'calculator': 'calculate',
  'chart': 'bar-chart',
  'graph': 'show-chart',
  'trending': 'trending-up',
  'analytics': 'analytics',
  'report': 'assessment',
  'document': 'description',
  'file': 'insert-drive-file',
  'folder': 'folder',
  'download': 'file-download',
  'upload': 'file-upload',
  'cloud': 'cloud',
  'sync': 'sync',
  'refresh': 'refresh',
  'reload': 'replay',
  'back': 'arrow-back',
  'forward': 'arrow-forward',
  'up': 'arrow-upward',
  'down': 'arrow-downward',
  'left': 'arrow-back-ios',
  'right': 'arrow-forward-ios',
  'menu': 'menu',
  'more': 'more-vert',
  'dots': 'more-horiz',
  'list': 'list',
  'grid': 'grid-view',
  'table': 'table-chart',
  'columns': 'view-column',
  'rows': 'view-list',
  'fullscreen': 'fullscreen',
  'fullscreen.exit': 'fullscreen-exit',
  'zoom.in': 'zoom-in',
  'zoom.out': 'zoom-out',
  'fit': 'fit-screen',
  'crop': 'crop',
  'rotate': 'rotate-right',
  'flip': 'flip',
  'mirror': 'flip-camera-ios',
  'flash': 'flash-on',
  'flash.off': 'flash-off',
  'flash.auto': 'flash-auto',
  'timer': 'timer',
  'timer.off': 'timer-off',
  'stopwatch': 'timer-10',
  'alarm': 'alarm',
  'bedtime': 'bedtime',
  'wake': 'wake-lock',
  'sun': 'wb-sunny',
  'moon': 'nightlight',
  'cloud.sun': 'wb-cloudy',
  'cloud.rain': 'grain',
  'cloud.snow': 'ac-unit',
  'wind': 'air',
  'thermometer': 'thermostat',
  'humidity': 'opacity',
  'pressure': 'speed',
  'uv': 'wb-sunny',
  'air.quality': 'air',
  'pollen': 'grass',
  'dust': 'grain',
  'smoke': 'smoke-free',
  'fire': 'whatshot',
  'flame': 'local-fire-department',
  'sparkles': 'auto-awesome',
  'bolt': 'flash-on',
  'zap': 'electric-bolt',
  'power': 'power',
  'power.off': 'power-off',
  'battery.25': 'battery-1-bar',
  'battery.50': 'battery-2-bar',
  'battery.75': 'battery-3-bar',
  'battery.100': 'battery-full',
  'battery.charging': 'battery-charging-full',
  'plug': 'power',
  'outlet': 'electrical-services',
  'lightbulb': 'lightbulb',
  'lightbulb.off': 'lightbulb-outline',
  'lamp': 'light',
  'candle': 'candle',
  'torch': 'flashlight-on',
  'lantern': 'lantern',
  'bulb': 'lightbulb',
  'switch': 'toggle-on',
  'switch.off': 'toggle-off',
  'button': 'radio-button-unchecked',
  'button.filled': 'radio-button-checked',
  'slider': 'linear-scale',
  'knob': 'rotate-right',
  'dial': 'speed',
  'lever': 'settings-input-component',
  'gear': 'settings',
  'cog': 'build',
  'wrench': 'build',
  'screwdriver': 'build',
  'hammer': 'handyman',
  'saw': 'content-cut',
  'drill': 'build',
  'soldering': 'build',
  'welding': 'build',
  'paint': 'format-paint',
  'brush': 'brush',
  'roller': 'format-paint',
  'spray': 'format-paint',
  'bucket': 'format-paint',
  'drop': 'opacity',
  'droplet': 'water-drop',
  'drop.fill': 'water-drop',
  'drop.half': 'opacity',
  'drop.off': 'opacity',
  'drop.slash': 'opacity',
  'drop.triangle': 'opacity',
  'drop.degreesign': 'opacity',
  'drop.circle': 'opacity',
  'drop.square': 'opacity',
  'drop.diamond': 'opacity',
  'drop.triangle.fill': 'opacity',
  'drop.degreesign.fill': 'opacity',
  'drop.circle.fill': 'opacity',
  'drop.square.fill': 'opacity',
  'drop.diamond.fill': 'opacity',
  'language': 'language',
  'notification': 'notifications',
  'bell': 'notifications',
  'person': 'person',
  'person.3': 'group',
  'car': 'directions-car',
  'ticket': 'confirmation-number',
  'star': 'star',
  'plus.circle': 'add-circle',
  'magnifyingglass': 'search',
  'location.fill': 'location-on',
  'person.3.fill': 'group',
  'wallet.pass': 'account-balance-wallet',
  'pencil': 'edit',
  'lock.fill': 'lock',
  'creditcard.fill': 'credit-card',
  'bell.fill': 'notifications',
  'questionmark.circle.fill': 'help',
  'envelope.fill': 'mail',
  'doc.text.fill': 'description',
  'checkmark.square.fill': 'check-box',
  'square': 'check-box-outline-blank',
  'rectangle.portrait.and.arrow.right': 'logout',
  'gearshape.fill': 'settings',
  'moon.fill': 'brightness-2',
  'sun.fill': 'brightness-5',
  'cart.fill': 'shopping-cart',
  'arrow.down.circle.fill': 'arrow-circle-down',
  'arrow.up.circle.fill': 'arrow-circle-up',
  'checkmark.circle.fill': 'check-circle',
  'dollarsign.circle.fill': 'account-balance-wallet',
  'clock.fill': 'access-time',
  'person.2.fill': 'group',
  'person.2': 'group',
} as unknown as IconMapping;

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 * This ensures a consistent look across platforms, and optimal resource usage.
 * Icon `name`s are based on SF Symbols and require manual mapping to Material Icons.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
